spring.datasource.url=jdbc:postgresql://localhost:5432/tech_db
spring.datasource.username=user_tech
spring.datasource.password=password_tech
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true